/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/redux/favSlice`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/map` | `/map`; params?: Router.UnknownInputParams; } | { pathname: `/config/Colors`; params?: Router.UnknownInputParams; } | { pathname: `/redux/busSlice`; params?: Router.UnknownInputParams; } | { pathname: `/redux/store`; params?: Router.UnknownInputParams; } | { pathname: `/screens/bus`; params?: Router.UnknownInputParams; } | { pathname: `/screens/search`; params?: Router.UnknownInputParams; } | { pathname: `/screens/stop`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/redux/favSlice`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/map` | `/map`; params?: Router.UnknownOutputParams; } | { pathname: `/config/Colors`; params?: Router.UnknownOutputParams; } | { pathname: `/redux/busSlice`; params?: Router.UnknownOutputParams; } | { pathname: `/redux/store`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/bus`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/search`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/stop`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/redux/favSlice${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/map${`?${string}` | `#${string}` | ''}` | `/map${`?${string}` | `#${string}` | ''}` | `/config/Colors${`?${string}` | `#${string}` | ''}` | `/redux/busSlice${`?${string}` | `#${string}` | ''}` | `/redux/store${`?${string}` | `#${string}` | ''}` | `/screens/bus${`?${string}` | `#${string}` | ''}` | `/screens/search${`?${string}` | `#${string}` | ''}` | `/screens/stop${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/redux/favSlice`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/map` | `/map`; params?: Router.UnknownInputParams; } | { pathname: `/config/Colors`; params?: Router.UnknownInputParams; } | { pathname: `/redux/busSlice`; params?: Router.UnknownInputParams; } | { pathname: `/redux/store`; params?: Router.UnknownInputParams; } | { pathname: `/screens/bus`; params?: Router.UnknownInputParams; } | { pathname: `/screens/search`; params?: Router.UnknownInputParams; } | { pathname: `/screens/stop`; params?: Router.UnknownInputParams; };
    }
  }
}
