services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - mongo_data:/data/db
    command: ["mongod", "--quiet", "--auth", "--logpath", "/dev/null"]
    networks:
      - mynetwork

  postgres:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_DB: static_data
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - mynetwork
        
  gateway:
    build: ./gateway
    container_name: gateway
    depends_on:
      - bus_model
    environment:
      MONGO_URI: "mongodb://admin:admin@mongodb:27017/?authSource=admin"
      POSTGRES_URI: "postgresql://admin:admin@postgres:5432/static_data"
      BUS_MODEL_URI: "http://bus_model:5002"
    volumes:
      - ./gateway:/gateway
    ports:
      - "5004:5004"
    networks:
      - mynetwork
    env_file:
      - .env

  training:
    build: ./training_data_collection
    container_name: training_data_collection
    depends_on:
      - mongodb
      - postgres
      - bus_model
    environment:
      MONGO_URI: "mongodb://admin:admin@mongodb:27017/?authSource=admin"
      POSTGRES_URI: "postgresql://admin:admin@postgres:5432/static_data"
      BUS_MODEL_URI: "http://bus_model:5002"
    volumes:
      - ./training_data_collection:/training_data_collection
    ports:
      - "5000:5000"
    networks:
      - mynetwork
    env_file:
      - .env

  bus_model:
    tty: true
    build: ./bus_model
    container_name: bus_model
    depends_on:
      - mongodb
      - postgres
    environment:
      MONGO_URI: "mongodb://admin:admin@mongodb:27017/?authSource=admin"
      POSTGRES_URI: "postgresql://admin:admin@postgres:5432/static_data"
      POSTGRES_DB_MADE_DIR: "/var/lib/bus_model/flags"
      INFERENCE_URI: "http://inference:5001"
      TRAINING_URI: "http://training_data_collection:5000"
      GATEWAY_URI: "http://gateway:5004"
    volumes:
      - ./bus_model:/bus_model
      - flags:/var/lib/bus_model/flags
    ports:
      - "5002:5002"
    networks:
      - mynetwork
    env_file:
      - .env

  inference:
    build: ./inference
    container_name: inference
    depends_on:
      - mongodb
      - postgres
    environment:
      MONGO_URI: "mongodb://admin:admin@mongodb:27017/?authSource=admin"
      POSTGRES_URI: "postgresql://admin:admin@postgres:5432/static_data"
      TRAINING_URI: "http://training_data_collection:5000"
    volumes:
      - ./inference:/inference
    ports:
      - "5001:5001"
    networks:
      - mynetwork
    env_file:
      - .env

networks:
  mynetwork:
    driver: bridge

volumes:
  mongo_data:
  pgdata:
  flags:
