export default {
    // backgroundPrimary: "#192124",
    // textPrimary: "#FFFFFF",
    // textSecondary: "#A9ACB3",
    // backgroundSecondary: "#01363E",
    // border: "darkgrey",
    // objectSelected: '#B2EDF5',
    // objectNotSelected: "#5F6268",
    backgroundPrimary: "black",
    textPrimary: "white",
    textSecondary: "#A9ACB3",
    textSwitchable: "black",
    backgroundSecondary: "#c9c3bb",
    border: "white",
    objectSelected: 'white',
    objectNotSelected: "#5F6268",
};